server:
  port: 8888
logging:
  level:
    com.jin.wechatReminder: info

openids: oYS9T6P-NQv4N4pJ5HuWsQZkKDSY,oYS9T6Ht2poRgl4I9MYnu0QjakWc,oYS9T6CVUHs-b9BZHu1bkwq2amSg

#wordurl: https://api.shadiao.pro/du
#wordurl: https://api.shadiao.pro/du
wordurl: https://api.shadiao.pro/du